namespace poberbimonitor;

permissionset 90100 powerbimonitor
{
    Assignable = true;
    Permissions = tabledata "PBI Dataflow Refresh History"=RIMD,
        tabledata "PBI Dataset Refresh History"=RIMD,
        tabledata "Power BI Dashboard"=RIMD,
        tabledata "Power BI Dataflow"=RIMD,
        tabledata "Power BI Dataset"=RIMD,
        tabledata "Power BI Report"=RIMD,
        tabledata "Power BI Setup"=RIMD,
        tabledata "Power BI Workspace"=RIMD,
        table "PBI Dataflow Refresh History"=X,
        table "PBI Dataset Refresh History"=X,
        table "Power BI Dashboard"=X,
        table "Power BI Dataflow"=X,
        table "Power BI Dataset"=X,
        table "Power BI Report"=X,
        table "Power BI Setup"=X,
        table "Power BI Workspace"=X,
        codeunit "Power BI API Orchestrator"=X,
        codeunit "Power BI Assisted Setup"=X,
        codeunit "Power BI Authentication"=X,
        codeunit "Power BI Auto Sync"=X,
        codeunit "Power BI Dashboard Manager"=X,
        codeunit "Power BI Dataflow Manager"=X,
        codeunit "Power BI Dataset Manager"=X,
        codeunit "Power BI Http Client"=X,
        codeunit "Power BI Json Processor"=X,
        codeunit "Power BI Report Manager"=X,
        codeunit "Power BI Workspace Manager"=X,
        page "PBI Dataflow Refresh History"=X,
        page "PBI Dataflow Refresh ListPart"=X,
        page "PBI Dataset Refresh History"=X,
        page "PBI Dataset Refresh ListPart"=X,
        page "PBI Report Dataset RefreshList"=X,
        page "Power BI Activities"=X,
        page "Power BI Dashboard"=X,
        page "Power BI Dashboard Card"=X,
        page "Power BI Dashboards"=X,
        page "Power BI Dataflows"=X,
        page "Power BI Dataflows Overview"=X,
        page "Power BI Datasets"=X,
        page "Power BI Datasets Overview"=X,
        page "Power BI Management"=X,
        page "Power BI Overview"=X,
        page "Power BI Recent Errors List"=X,
        page "Power BI Refresh Errors"=X,
        page "Power BI Reports"=X,
        page "Power BI Resources Overview"=X,
        page "Power BI Role Center"=X,
        page "Power BI Setup"=X,
        page "Power BI Setup Wizard"=X,
        page "Power BI Workspaces"=X,
        page "Power BI Workspaces Overview"=X;
}